import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

1) Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

 there is a difference in the data type of variables list_ and array_list
 The variable list_ is a Python list data type 
 the variable array_list is a NumPy array data type
 

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


2) Write a code to print the data type of each and every element of both the variables list_ and
arra_list. 

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


3) Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [3]:
import numpy as np
list = ['1','2','3','4','5']
array_list = np.array(list, dtype = int)
print("Data type of each element in list:")
for element in list:
    print(type(element))
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


4) Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
import numpy as np
arr = np.random.randint(1,10,[3,4])

In [8]:
print(arr.shape)
print(arr.size)


(3, 4)
12


5) Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.


In [10]:
import numpy as np

arr1 = np.zeros((3, 3))
print(arr1)
print(arr1.shape)
print(arr1.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9


6) Create an identity matrix of shape (5,5) using numpy functions?

In [11]:
import numpy as np
arr2 =np.eye(5)
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])